version: '3.9'

services:
  app:
    build: .
    entrypoint: './bin/entrypoint.sh'
    ports:
      - '$APP_PORT:$APP_PORT'
    volumes:
      - .:$PROJECT_LOCATION
    env_file:
      - .env
    networks:
      app_network:
        ipv4_address: $NETWORK_PREFIX.2

  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - '$DB_PORT:DB_EXT_PORT'
    volumes:
      - db:/var/lib/mysql
    networks:
      app_network:
        ipv4_address: $NETWORK_PREFIX.3

volumes:
  db:
    driver: local

networks:
  app_network:
    ipam:
      config:
        - subnet: $NETWORK_PREFIX.0/16
