version: '3.9'

services:
  app:
    build: .
    command: npm run watch
    ports:
      - '$APP_PORT:$APP_PORT'
    volumes:
      - .:$PROJECT_LOCATION
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      poster_network:
        ipv4_address: $NETWORK_PREFIX.2

  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - '$DB_PORT:$DB_PORT'
    volumes:
      - db:/var/lib/mysql
    networks:
      poster_network:
        ipv4_address: $NETWORK_PREFIX.3
volumes:
  db:
    driver: local

networks:
  poster_network:
    ipam:
      config:
        - subnet: $NETWORK_PREFIX.0/16
